### ISSUE TITLE
The control icons ( + or - ) are no longer centered when a responsive datatable has the Semantic UI 'compact' class 

### ISSUE THREAD

**Issue by kmd1970** [DataTables/DataTables#925]
When the Semantic UI `compact` class is added to a responsive datatable, the control icons ( + or - ) become off centered.

![table](http://i.imgur.com/k3F438e.jpg)

This can be fixed with the following css.
```css
table.dataTable.dtr-inline.collapsed.compact > tbody > tr > td:first-child::before, 
table.dataTable.dtr-inline.collapsed.compact > tbody > tr > th:first-child::before {
    text-indent: 0 !important;
}
```
